---
title: "Untitled"
author: "Cheng Gao"
date: "4/5/2019"
output: html_document
---


```{r, fig.height = 8, fig.width = 12, fig.align = "center"}
setwd("/Users/chengg/Google Drive/EPICON/Mycobiome/Fungal ITS/statistic/Total.fungi")
library(TITAN2)
library(ggplot2)
rm(list = ls())
load("TITAN.Rdata")
load("EPICON.data.preparation.RC.bNTI.ghost.2019.03.17.Rdata")


da1<-da2<-titan.out<-data.frame(titan.root.control$sppmax)
da1<-da1[da1$filter==1,]
da1<-da1[order(-da1$zenv.cp),]
da2<-da2[da2$filter==2,]
da2<-da2[order(da2$zenv.cp),]
da<-data.frame(rbind(da1,da2))
da$name<-row.names(da)
ID0<-ID
ID1<-ID0[ID0$OTU.ID.1 %in%row.names(da1),]
dax<-merge(da, ID, by.x = "name", by.y = "OTU.ID.1", all =FALSE)

dax<-dax[match(da$name, dax$name),]
dax$ord<-c(1:length(dax$name))
dax$titan<-factor(dax$filter)
levels(dax$titan)<-c("z-", "z+")
da.root<-dax

da1<-da2<-titan.out<-data.frame(titan.leaf.control$sppmax)
da1<-da1[da1$filter==1,]
da1<-da1[order(-da1$zenv.cp),]
da2<-da2[da2$filter==2,]
da2<-da2[order(da2$zenv.cp),]
da<-data.frame(rbind(da1,da2))
da$name<-row.names(da)
ID0<-ID
ID1<-ID0[ID0$OTU.ID.1 %in%row.names(da1),]
dax<-merge(da, ID, by.x = "name", by.y = "OTU.ID.1", all =FALSE)
dax<-dax[match(da$name, dax$name),]
dax$ord<-c(1:length(dax$name))
dax$titan<-factor(dax$filter)
levels(dax$titan)<-c("z-", "z+")
da.leaf<-dax

da1<-da2<-titan.out<-data.frame(titan.rhizosphere.control$sppmax)
da1<-da1[da1$filter==1,]
da1<-da1[order(-da1$zenv.cp),]
da2<-da2[da2$filter==2,]
da2<-da2[order(da2$zenv.cp),]
da<-data.frame(rbind(da1,da2))
da$name<-row.names(da)
ID0<-ID
ID1<-ID0[ID0$OTU.ID.1 %in%row.names(da1),]
dax<-merge(da, ID, by.x = "name", by.y = "OTU.ID.1", all =FALSE)
dax<-dax[match(da$name, dax$name),]
dax$ord<-c(1:length(dax$name))
dax$titan<-factor(dax$filter)
levels(dax$titan)<-c("z-", "z+")
da.rhizosphere<-dax

da1<-da2<-titan.out<-data.frame(titan.soil.control$sppmax)
da1<-da1[da1$filter==1,]
da1<-da1[order(-da1$zenv.cp),]
da2<-da2[da2$filter==2,]
da2<-da2[order(da2$zenv.cp),]
da<-data.frame(rbind(da1,da2))
da$name<-row.names(da)
ID0<-ID
ID1<-ID0[ID0$OTU.ID.1 %in%row.names(da1),]
dax<-merge(da, ID, by.x = "name", by.y = "OTU.ID.1", all =FALSE)
dax<-dax[match(da$name, dax$name),]
dax$ord<-c(1:length(dax$name))
dax$titan<-factor(dax$filter)
levels(dax$titan)<-c("z-", "z+")
da.soil<-dax
da.soil$Habitat="Soil"
da.root$Habitat="Root"
da.leaf$Habitat="Leaf"
da.rhizosphere$Habitat="Rhizosphere"

dax<-data.frame(rbind(da.leaf,da.root,da.rhizosphere,da.soil))
dax$Habitat<-factor(dax$Habitat, levels=c("Leaf","Root", "Rhizosphere", "Soil"))
dax$Titan<-dax$titan
ggplot( )+
  geom_text(data=dax,aes(x=ord+0.5, y=zenv.cp+2, label = Genus,color = Guild), size = 3)+
  geom_pointrange(data=dax,aes(x=ord, y=zenv.cp, ymin=X5., ymax=X95.,color = Guild, shape = Titan, linetype=Titan), size =0.8)+
  scale_shape_manual(values=c(16, 1)) + coord_flip() + ylab("Week") + xlab("OTUs") + 
  scale_y_continuous(breaks=c(1,3,5,7,9,11,13,15,17))+
  facet_wrap(~Habitat, nrow = 1,strip.position= 'top',scales ="free_y")+
  theme(panel.background = element_rect(fill = NA)) + 
  guides(color=guide_legend(title= "Fungal guild"))+
  theme(strip.text = element_text(size = 15,face="bold"),
        legend.title = element_text(colour="black", size=20, face="bold"),
        legend.text = element_text(colour="black", size=20, face="bold"),
        axis.text = element_text(size = 10, face = "bold"),
        axis.title=element_text(size=20,face="bold"),
        axis.line = element_line(linetype = "solid"))+
  scale_color_manual(values=c("green","blue","purple","black","chocolate", "red","grey"))
```


```{r, fig.height = 4, fig.width = 12, fig.align = "center"}
ggplot( )+
  #geom_text(data=dax,aes(x=ord+0.5, y=zenv.cp+2, label = Genus,color = Guild), size = 3)+
  geom_pointrange(data=dax,aes(x=ord, y=zenv.cp, ymin=X5., ymax=X95.,color = Guild, shape = Titan, linetype=Titan), size =0.8)+
  scale_shape_manual(values=c(16, 1)) + coord_flip() + ylab("Week") + xlab("OTUs") + 
  scale_y_continuous(breaks=c(1,3,5,7,9,11,13,15,17))+
  facet_wrap(~Habitat, nrow = 1,strip.position= 'top',scales ="free_y")+
  theme(panel.background = element_rect(fill = NA)) + 
  guides(color=guide_legend(title= "Fungal guild"))+
  theme(strip.text = element_text(size = 15,face="bold"),
        legend.title = element_text(colour="black", size=20, face="bold"),
        legend.text = element_text(colour="black", size=20, face="bold"),
        axis.text = element_text(size = 10, face = "bold"),
        axis.title=element_text(size=20,face="bold"),
        axis.line = element_line(linetype = "solid"))+
  scale_color_manual(values=c("green","blue","purple","black","chocolate", "red","grey"))
```

