---
title: "Untitled"
author: "Cheng Gao"
date: "3/18/2019"
output: html_document
---


```{r}
setwd("/Users/chengg/Google Drive/EPICON/Mycobiome/Fungal ITS/statistic/Total.fungi")
library(reshape2)
library(ggplot2)
library(MASS)
library(splitstackshape)
library(colorRamps)
rm(list = ls())
rm(list = ls())

load("EPICON.data.preparation.RC.bNTI.ted.2019.04.19.Rdata")


BarPlt<- function (opf, title, colo) {
  gr<-fung0$Fungi=="Fungi"
  fungt<-data.frame(fung0[gr ,c(1:1251) ]) ### raw data of all samples including pseudo samples #
  ID<-data.frame(fung0[gr ,c(-1:-1251) ]) ### raw data of all samples including pseudo samples #
  ID$Guild<-factor(ID$Guild, labels = c("Arbuscular_mycorrhiza", "Endophyte", "Plant_pathogen", "Plant_pathogen_Yeast", "Saprotroph", "Saprotroph_Yeast", "Others" ))
  Flev<-ID[,opf] 
  fung.lev<-data.frame(aggregate(fungt,by=list(Flev) , sum))
  rownames(fung.lev)<-fung.lev[,1]; fung.lev<-fung.lev[,-1]
  fung1<-data.frame(t(fung.lev))
  
  fung.raw.pseudo<-fung1[env0$Habitat!="Prop_root",]  # can be useful for Barplots of total fungi
  env.F.raw.pseudo<-env0[env0$Habitat!="Prop_root",]   # can be useful for Barplots of total fungi
  
  fung.raw<-fung.raw.pseudo[c(1:1026),] ### raw data of all samples #
  env.raw<-env.F.raw.pseudo[c(1:1026),]
  
  # relative abundance
  total<-apply(fung.raw, 1, sum); 
  fung.relabu<-data.frame(lapply(fung.raw, function(x) {  x / total  }) )  # change the abundance data into relative abundance#
  
  fung.L<-fung.relabu
  env.L<-env.raw
  
  fung.L <- fung.L[,order(sort(colnames(fung.L)))] ## 
  lev<-interaction(env.L$Habitat, env.L$TP, env.L$Treatment1, env.L$Cultivar,sep = ":") ## ccombining factors for Barplot profiling
  fung.L.lev<-aggregate(fung.L,by=list(lev) , mean) # generate the mean for each factor level
  fung.L1<-fung.L.lev[,c(1,2:ncol(fung.L.lev))] # the domiant OTUs
  fung.L1 <- melt(fung.L1,id.vars = "Group.1")
  fung.bind<-cSplit(fung.L1, "Group.1", ":")
  names(fung.bind)<-c("Fungi","Relative_Abundance", "Habitat", "TP", "Treatment", "Cultivar")
  
  fung.bind$Treatment<-factor(fung.bind$Treatment,levels=c("Control", "Pre_flowering_drought", "Post_flowering_drought"), labels = c("CON", "PRE", "POST"))
  fung.bind$Habitat<-factor(fung.bind$Habitat,levels=c("Leaf", "Root", "Rhizosphere", "Soil"), labels = c("Leaf", "Root", "Rhizosphere", "Soil"))
  
  
  ggplot(fung.bind, aes(x = factor(TP), y = Relative_Abundance, fill=Fungi)) +
    geom_bar(stat='identity', position = "fill")+  
    labs(x="Week",y = "Relative abundance")+
    facet_grid(Treatment+Cultivar~Habitat)+
    guides(fill=guide_legend(title= title))+theme_bw()+
    theme(strip.text = element_text(size = 20,face="bold"),
          panel.spacing = unit(0, "lines"),
          legend.title = element_text(colour="black", size=20, face="bold"),
          legend.text = element_text(colour="black", size=20, face="bold"),
          axis.text.y=element_text(size=10,face="bold"),
          axis.text.x=element_text(size=14,face="bold",angle = 90),
          axis.title=element_text(size=20,face="bold"))+
    scale_y_continuous(labels = scales::percent)+
    scale_fill_manual(values= colo) 
}

```


```{r,  fig.height = 10, fig.width = 17, fig.align = "center"}
BarPlt("Guild", "Fungal guilds", c("green","blue","purple","black","chocolate", "red","grey"))
col11<-c("#ff00ff","#00ff00", "deepskyblue", "gold", "red", "navy", "darkgreen","maroon3", "black", "bisque", "grey")
BarPlt("Phylum.ab","Fungal phylum", col11)

```



```{r,  fig.height = 10, fig.width = 17, fig.align = "center"}
rm(list = ls())


load("EPICON.data.preparation.RC.bNTI.ted.2019.04.19.Rdata")

col11<-c("#ff00ff","#00ff00", "deepskyblue", "gold", "red", "navy", "darkgreen","maroon3", "black", "bisque", "grey")

gr<-fung0$Fungi=="Fungi"
fungt<-data.frame(fung0[gr ,c(1:1251) ]) ### raw data of all samples including pseudo samples #
ID<-data.frame(fung0[gr ,c(-1:-1251) ]) ### raw data of all samples including pseudo samples #

fung1<-data.frame(t(fungt))
fung.raw.pseudo<-fung1[env0$Habitat!="Prop_root",]  # can be useful for Barplots of total fungi
env.F.raw.pseudo<-env0[env0$Habitat!="Prop_root",]   # can be useful for Barplots of total fungi

fung.raw<-fung.raw.pseudo[c(1:1026),] ### raw data of all samples #
env.raw<-env.F.raw.pseudo[c(1:1026),]

# relative abundance
total<-apply(fung.raw, 1, sum); 
fung.relabu<-data.frame(lapply(fung.raw, function(x) {  x / total  }) )  # change the abundance data into relative abundance#

fung.L<-fung.relabu
env.L<-env.raw

fung.L <- fung.L[,order(sort(colnames(fung.L)))] ## 
lev<-interaction(env.L$Habitat, env.L$TP, env.L$Treatment1, env.L$Cultivar,sep = ":") ## ccombining factors for Barplot profiling
fung.L.lev<-aggregate(fung.L,by=list(lev) , mean) # generate the mean for each factor level
fung.L1<-fung.L.lev[,c(1,2:11)] # the domiant OTUs
fung.L1 <- melt(fung.L1,id.vars = "Group.1")
fung.L1<-cSplit(fung.L1, "Group.1", ":")
names(fung.L1)<-c("Fungi","Relative_Abundance", "Habitat", "TP", "Treatment", "Cultivar")

fung.L2<-fung.L.lev[,c(1,12:ncol(fung.L.lev))] # the rare OTUs, combined as 'others'
fung.L2 <- melt(fung.L2,id.vars = "Group.1")
fung.L2<-cSplit(fung.L2, "Group.1", ":")
names(fung.L2)<-c("Fungi","Relative_Abundance","Habitat", "TP", "Treatment", "Cultivar")
fung.L2$Fungi<-"Other"

fung.bind<-rbind(fung.L1,fung.L2) # combine the domiant and rare OTUs
fung.bind$Treatment<-factor(fung.bind$Treatment,levels=c("Control", "Pre_flowering_drought", "Post_flowering_drought"), labels = c("CON", "PRE", "POST"))
fung.bind$Habitat<-factor(fung.bind$Habitat,levels=c("Leaf", "Root", "Rhizosphere", "Soil"), labels = c("Leaf", "Root", "Rhizosphere", "Soil"))


ggplot(fung.bind, aes(x = factor(TP), y = Relative_Abundance, fill=Fungi)) +
  geom_bar(stat='identity', position = "fill")+  
  labs(x="Week",y = "Relative abundance")+
  facet_grid(Treatment+Cultivar~Habitat)+
  scale_fill_manual(values= col11)+ theme_bw()+
  guides(fill=guide_legend(title= "Fungal OTUs"))+
  theme(strip.text = element_text(size = 20,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=20, face="bold"),
        legend.text = element_text(colour="black", size=20, face="bold"),
        axis.text.y=element_text(size=10,face="bold"),
        axis.text.x=element_text(size=14,face="bold",angle = 90),
        axis.title=element_text(size=20,face="bold"))+
  scale_y_continuous(labels = scales::percent)
```

