---
title: "Untitled"
author: "Cheng Gao"
date: "4/5/2019"
output: html_document
---

```{r, fig.height = 8, fig.width = 12, fig.align = "center"}
# Manhatan  drought
library(ggrepel)
library(vegan)
library(dplyr)
rm(list = ls())
load("EPICON.data.preparation.RC.bNTI.ghost.2019.03.17.Rdata")


otu_table0<-data.frame(t(fung.raw)) ##Read in the raw data###
row.names(otu_table0)<-row.names(ID)
otu_table1<-data.frame(t(otu_table0[ID$Kingdom=="Fungi",]))
env$Treatment1<-factor(env$Treatment1,levels=c("Control", "Pre_flowering_drought", "Post_flowering_drought"))

manhatan.drought<- function (habitat,tp, Ntreat, treat)
{
  fung<-otu_table1[env$Habitat == habitat, ]
  fung<-fung[,colSums(fung)>0]
  subse<- env$Habitat == habitat & env$TP> tp & env$Treatment1 != Ntreat
  fung.subs<-otu_table1[subse,]
  set.seed(315)
  
  fung.subs<-data.frame(rrarefy(fung.subs, min(rowSums(fung.subs))))
  com<-fung.subs[,colSums(fung.subs)>0]
  env.subs<-env[subse,]
  va<-env.subs[, treat]
  paov<-adonis(com~va)
  print(paov)
  dvoc<-data.frame()
  for (i in c(1: ncol(com)))
  {
    tt<-t.test(com[,i]~va)  # t test
    p<-tt$p.value           # pvalue of t test
    name<-colnames(com)[i]  # OTU name
    fs<-aggregate(com[,i], by=list(va), FUN=mean) # mean abundance of OTU in two habitats
    fc<-log2((fs[1,2]+1)/(fs[2,2]+1))  
    abu<-log2(colSums(com)[i]/nrow(com)+1)
    dd<-data.frame(fc,p,   name,abu, i, " ")
    dvoc<-rbind(dvoc, dd)
  }
  dvoc<-data.frame(dvoc)
  names(dvoc)<-c("log2FoldChange", "pvalue","name", "log2AverageAbundance", "order", "Group")
  dvoc$padj<-p.adjust(dvoc$pvalue, n = length(dvoc$pvalue))
  dvoc$neglogp = -log(dvoc$pvalue)
  
  dvoc$level = as.factor(ifelse( dvoc$log2FoldChange > 0, "Control > Drought", "Drought > Control"))
  dvoc$level<-factor(dvoc$level,levels=c("Control > Drought","Drought > Control"))
  
  x<-droplevels(merge(dvoc,ID,  by.y = "OTU.ID.1", by.x = "name", all = FALSE))
  x = arrange(x, Guild,Genus,log2AverageAbundance,neglogp)
  x<-x[order(x$Guild),]
  x$name = factor(x$name, levels=x$name) 
  x1<-droplevels(x[x$neglogp >=10,])
  pos<-droplevels(x1[x1$log2FoldChange>0,])
  neg<-droplevels(x1[x1$log2FoldChange<0,])
  print(pos$name)
  print(neg$name)
  p1<-ggplot(x, aes(x=name, y=neglogp, color=Guild, size=log2AverageAbundance, shape=level)) +
    geom_point(alpha = 0.6) + 
    geom_text_repel(data=subset(x, neglogp > 10),vjust="inward",hjust="inward", 
                    aes(label=Genus), angle = 0, size=3, color="black",fontface= "bold")+
    geom_hline(yintercept= 10, linetype=1, color="green") +
    scale_shape_manual(values=c(1, 2))+
    scale_size(breaks=c(5, 10, 15)) +
    labs(x=" ", y=" ") + 
    scale_color_manual(values=c("green","blue","purple","black","chocolate", "red","grey"))+
    theme(axis.ticks.x=element_blank(),axis.text.x=element_blank())+
    theme(panel.background = element_rect(fill = NA),legend.position = "none") + 
    labs(title = habitat, x = "", y=" ", size = "log(Average Abundance)", shape = "Sorghum effect") +
    theme(axis.line = element_line(linetype = "solid"))  +
    theme(axis.text.y = element_text(size = 12)) +
    theme(axis.text.y = element_text(colour = "black"))
  return(p1)
}

manhatan.drought("Leaf", 2, "Post_flowering_drought","Treatment1" )
manhatan.drought("Leaf", 9, "Pre_flowering_drought","Treatment1" )

manhatan.drought("Root", 2, "Post_flowering_drought","Treatment1" )
manhatan.drought("Root", 9, "Pre_flowering_drought","Treatment1" )

manhatan.drought("Rhizosphere", 2, "Post_flowering_drought","Treatment1" )
manhatan.drought("Rhizosphere", 9, "Pre_flowering_drought","Treatment1" )

manhatan.drought("Soil", 2, "Post_flowering_drought","Treatment1" )
manhatan.drought("Soil", 9, "Pre_flowering_drought","Treatment1" )


```

```{r, fig.height = 3, fig.width = 3, fig.align = "center"}
manhatan.drought<- function (habitat,tp, Ntreat, treat)
{
  fung<-otu_table1[env$Habitat == habitat, ]
  fung<-fung[,colSums(fung)>0]
  subse<- env$Habitat == habitat & env$TP> tp & env$Treatment1 != Ntreat
  fung.subs<-otu_table1[subse,]
  set.seed(315)
  
  fung.subs<-data.frame(rrarefy(fung.subs, min(rowSums(fung.subs))))
  com<-fung.subs[,colSums(fung.subs)>0]
  env.subs<-env[subse,]
  va<-env.subs[, treat]
  paov<-adonis(com~va)
  print(paov)
  dvoc<-data.frame()
  for (i in c(1: ncol(com)))
  {
    tt<-t.test(com[,i]~va)  # t test
    p<-tt$p.value           # pvalue of t test
    name<-colnames(com)[i]  # OTU name
    fs<-aggregate(com[,i], by=list(va), FUN=mean) # mean abundance of OTU in two habitats
    fc<-log2((fs[1,2]+1)/(fs[2,2]+1))  
    abu<-log2(colSums(com)[i]/nrow(com)+1)
    dd<-data.frame(fc,p,   name,abu, i, " ")
    dvoc<-rbind(dvoc, dd)
  }
  dvoc<-data.frame(dvoc)
  names(dvoc)<-c("log2FoldChange", "pvalue","name", "log2AverageAbundance", "order", "Group")
  dvoc$padj<-p.adjust(dvoc$pvalue, n = length(dvoc$pvalue))
  dvoc$neglogp = -log(dvoc$pvalue)
  
  dvoc$level = as.factor(ifelse( dvoc$log2FoldChange > 0, "Control > Drought", "Drought > Control"))
  dvoc$level<-factor(dvoc$level,levels=c("Control > Drought","Drought > Control"))
  
  x<-droplevels(merge(dvoc,ID,  by.y = "OTU.ID.1", by.x = "name", all = FALSE))
  x = arrange(x, Guild,Genus,log2AverageAbundance,neglogp)
  x<-x[order(x$Guild),]
  x$name = factor(x$name, levels=x$name) 
  x1<-droplevels(x[x$neglogp >=10,])
  pos<-droplevels(x1[x1$log2FoldChange>0,])
  neg<-droplevels(x1[x1$log2FoldChange<0,])
  print(pos$name)
  print(neg$name)
  p1<-ggplot(x, aes(x=name, y=neglogp, color=Guild, size=log2AverageAbundance, shape=level)) +
    geom_point(alpha = 0.6) + 
    #geom_text_repel(data=subset(x, neglogp > 10),vjust="inward",hjust="inward", 
    #                aes(label=Genus), angle = 0, size=3, color="black",fontface= "bold")+
    geom_hline(yintercept= 10, linetype=1, color="green") +
    scale_shape_manual(values=c(1, 2))+
    scale_size(breaks=c(5, 10, 15)) +
    labs(x=" ", y=" ") + 
    scale_color_manual(values=c("green","blue","purple","black","chocolate", "red","grey"))+
    theme(axis.ticks.x=element_blank(),axis.text.x=element_blank())+
    theme(panel.background = element_rect(fill = NA),legend.position = "none") + 
    labs(title = habitat, x = "", y=" ", size = "log(Average Abundance)", shape = "Sorghum effect") +
    theme(axis.line = element_line(linetype = "solid"))  +
    theme(axis.text.y = element_text(size = 12)) +
    theme(axis.text.y = element_text(colour = "black"))
  return(p1)
}

manhatan.drought("Leaf", 2, "Post_flowering_drought","Treatment1" )
manhatan.drought("Leaf", 9, "Pre_flowering_drought","Treatment1" )

manhatan.drought("Root", 2, "Post_flowering_drought","Treatment1" )
manhatan.drought("Root", 9, "Pre_flowering_drought","Treatment1" )

manhatan.drought("Rhizosphere", 2, "Post_flowering_drought","Treatment1" )
manhatan.drought("Rhizosphere", 9, "Pre_flowering_drought","Treatment1" )

manhatan.drought("Soil", 2, "Post_flowering_drought","Treatment1" )
manhatan.drought("Soil", 9, "Pre_flowering_drought","Treatment1" )


```

