---
title: "Untitled"
author: "Cheng Gao"
date: "12/3/2018"
output: html_document
---

```{r, message=FALSE, warning=FALSE, fig.height = 4, fig.width = 11}
setwd("/Users/chengg/Google\ Drive/EPICON/Y17/2018.10.22")
library(reshape2)
library(ggplot2)
library(MASS)
library(splitstackshape)
library(colorRamps)
library(vegan)
library(ape)
env0<-read.csv("EPICON.ENV.2018.10.22.csv", head = T)
fung.raw<-read.csv("EPICON.FUNIGI.matrix.ID.2018.10.22.csv", head = T, row.names = 1)
ID0<-fung.raw[,c(1667:1692)]
fung0<-fung.raw[,c(1:1666)]

lev<-ID0$Fungi == "Fungi"
fung<-data.frame(t(fung0[lev,]))
ID<-ID0[lev,]

Slev<- (env0$Habitat=="A" | env0$Habitat=="B" | env0$Habitat=="C" | env0$Habitat=="P" ) 
envA<-droplevels(env0[Slev,])
fungA<-fung[Slev,]
fungA<-rrarefy(fungA, 17014)
envA$X<-as.numeric(as.character(envA$Cultivar))
envA$Y<-as.numeric(as.character(envA$Treatment1))
fung.pc<-pcoa(vegdist(decostand(fungA,"hellinger"),"bray"))
envpc<-data.frame(fung.pc$vectors, envA)

envpc$Habitat<-factor(envpc$Habitat, labels =c("A", "B", "C", "0"))

ggplot() + geom_point(data=envpc,aes(x= Axis.1, y=Axis.2,colour= factor(plot), shape=Habitat),  size=3, alpha = 0.7, stroke = 3) + 
  labs(x = "PCo1",y = "PCo2")+
  facet_wrap(~Sampletime)+
  scale_shape_manual(values = c(0, 6, 1, 3))+
  scale_color_manual(values =c(c("#ff00ff","#00ff00", "deepskyblue", "gold", "red", "navy", "darkgreen","maroon3", "black", "bisque", "grey")))+
  guides(colour=guide_legend(title= "Location"),shape=guide_legend(title= "Direction"))+
  theme_bw()+
  theme(strip.text = element_text(size = 15,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=15, face="bold"),
        legend.text = element_text(colour="black", size=15, face="bold"),
        axis.text=element_text(size=10,face="bold"),
        axis.text.x=element_text(angle = 90),
        axis.title=element_text(size=15,face="bold"))


ggplot() + geom_point(data=envpc,aes(x= Axis.1, y=Axis.2,colour= factor(plot), shape=Habitat),  size=3, alpha = 0.7, stroke = 3) + 
  labs(x = "PCo1",y = "PCo2")+
  facet_wrap(~Sampletime)+
  scale_shape_manual(values = c(0, 6, 1, 3))+
  scale_color_manual(values =c(c("#ff00ff","#00ff00", "deepskyblue", "gold", "red", "navy", "darkgreen","maroon3", "black", "bisque", "grey")))+
  guides(colour="none",shape="none")+
  theme_bw()+
  theme(strip.text = element_text(size = 15,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=15, face="bold"),
        legend.text = element_text(colour="black", size=15, face="bold"),
        axis.text=element_text(size=10,face="bold"),
        axis.text.x=element_text(angle = 90),
        axis.title=element_text(size=15,face="bold"))

Slev<- (env0$Habitat=="A" | env0$Habitat=="B" | env0$Habitat=="C" | env0$Habitat=="P" ) &  env0$Sampletime == "TP0913"
envA<-droplevels(env0[Slev,])
fungA<-fung[Slev,]
fungA<-rrarefy(fungA, 17014)
envA$X<-as.numeric(as.character(envA$Cultivar))
envA$Y<-as.numeric(as.character(envA$Treatment1))
bc<-vegdist(decostand(fungA,"hellinger"),"bray")
gd<-dist(cbind(envA$X, envA$Y))
mantel(bc,gd)
da1<-data.frame(cbind(gd, bc), TP="TP0913")

Slev<- (env0$Habitat=="A" | env0$Habitat=="B" | env0$Habitat=="C" | env0$Habitat=="P" ) &  env0$Sampletime == "TP1011"
envA<-droplevels(env0[Slev,])
fungA<-fung[Slev,]
fungA<-rrarefy(fungA, 17014)
envA$X<-as.numeric(as.character(envA$Cultivar))
envA$Y<-as.numeric(as.character(envA$Treatment1))
bc<-vegdist(decostand(fungA,"hellinger"),"bray")
gd<-dist(cbind(envA$X, envA$Y))
mantel(bc,gd)
da2<-data.frame(cbind(gd, bc), TP="TP1011")

da<-rbind(da1,da2)
ggplot() + geom_point(data=da,aes(x= gd * 7.5, y=bc),  size=3, alpha = 0.2, stroke = 3) + 
  labs(x = "Geographic distance (m)",y = "Bray-Curtis dissimilarity")+
  ylim(0,1)+
  facet_wrap(~TP)+
  theme_bw()+
  theme(strip.text = element_text(size = 15,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=15, face="bold"),
        legend.text = element_text(colour="black", size=15, face="bold"),
        axis.text=element_text(size=10,face="bold"),
        axis.title=element_text(size=15,face="bold"))
```


```{r, message=FALSE, warning=FALSE, fig.height = 3, fig.width = 7}

Slev<- (env0$Habitat=="A" | env0$Habitat=="B" | env0$Habitat=="C" | env0$Habitat=="P" ) 
envA<-droplevels(env0[Slev,])
fungA<-fung[Slev,]
fungA<-rrarefy(fungA, 17014)
envA$X<-as.numeric(as.character(envA$Cultivar))
envA$Y<-as.numeric(as.character(envA$Treatment1))
bc<-vegdist(decostand(fungA,"hellinger"),"bray")
gd<-dist(cbind(envA$X, envA$Y))
mantel(bc,gd)
da<-data.frame(cbind(gd, bc))
ggplot() + geom_point(data=da,aes(x= gd * 7.5, y=bc),  size=3, alpha = 0.2, stroke = 3) + 
  labs(x = "Geographic distance (m)",y = "Bray-Curtis dissimilarity")+
  ylim(0,1)+
  theme_bw()+
  theme(strip.text = element_text(size = 15,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=15, face="bold"),
        legend.text = element_text(colour="black", size=15, face="bold"),
        axis.text=element_text(size=10,face="bold"),
        axis.title=element_text(size=15,face="bold"))


Slev<- (env0$Habitat=="A" | env0$Habitat=="B" | env0$Habitat=="C" | env0$Habitat=="P" ) &  env0$Sampletime == "TP0913"
envA<-droplevels(env0[Slev,])
fungA<-fung[Slev,]
fungA<-rrarefy(fungA, 17014)
envA$X<-as.numeric(as.character(envA$Cultivar))
envA$Y<-as.numeric(as.character(envA$Treatment1))
bc<-vegdist(decostand(fungA,"hellinger"),"bray")
gd<-dist(cbind(envA$X, envA$Y))
mantel(bc,gd)

da<-data.frame(cbind(gd, bc))
ggplot() + geom_point(data=da,aes(x= gd * 7.5, y=bc),  size=3, alpha = 0.2, stroke = 3) + 
  labs(x = "Geographic distance (m)",y = "Bray-Curtis dissimilarity")+
  ylim(0,1)+
  theme_bw()+
  theme(strip.text = element_text(size = 15,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=15, face="bold"),
        legend.text = element_text(colour="black", size=15, face="bold"),
        axis.text=element_text(size=10,face="bold"),
        axis.title=element_text(size=15,face="bold"))



Slev<- (env0$Habitat=="A" | env0$Habitat=="B" | env0$Habitat=="C" | env0$Habitat=="P" ) &  env0$Sampletime == "TP1011"
envA<-droplevels(env0[Slev,])
fungA<-fung[Slev,]
fungA<-rrarefy(fungA, 17014)
envA$X<-as.numeric(as.character(envA$Cultivar))
envA$Y<-as.numeric(as.character(envA$Treatment1))
bc<-vegdist(decostand(fungA,"hellinger"),"bray")
gd<-dist(cbind(envA$X, envA$Y))
mantel(bc,gd)
da<-data.frame(cbind(gd, bc))
ggplot() + geom_point(data=da,aes(x= gd * 7.5, y=bc),  size=3, alpha = 0.2, stroke = 3) + 
  labs(x = "Geographic distance (m)",y = "Bray-Curtis dissimilarity")+
  ylim(0,1)+
  theme_bw()+
  theme(strip.text = element_text(size = 15,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=15, face="bold"),
        legend.text = element_text(colour="black", size=15, face="bold"),
        axis.text=element_text(size=10,face="bold"),
        axis.title=element_text(size=15,face="bold"))




```


```{r, message=FALSE, warning=FALSE, fig.height = 4, fig.width = 11}
Slev<- (env0$Habitat=="A" | env0$Habitat=="B" | env0$Habitat=="C" | env0$Habitat=="P" ) 
envA<-droplevels(env0[Slev,])
fungA<-fung[Slev,]


env.L<-envA
fung.L<-fungA

total<-apply(fung.L, 1, sum); fung2<-data.frame(lapply(fung.L, function(x) {  x / total  }) ) *100 # change the abundance data into relative abundance#

lev<-interaction(env.L$Sampletime, env.L$Habitat, env.L$plot, sep = ":") ## ccombining factors for Barplot profiling
fung.L.lev<-aggregate(fung.L,by=list(lev) , mean) # generate the mean for each factor level
fung.L1<-fung.L.lev[,c(1,2:10)] # the domiant OTUs
fung.L1 <- melt(fung.L1,id.vars = "Group.1")
fung.L1<-cSplit(fung.L1, "Group.1", ":")
names(fung.L1)<-c("Fungi","Relative_Abundance", "Sampletime", "Direction", "Distance")

fung.L2<-fung.L.lev[,c(1,11:ncol(fung.L.lev))] # the rare OTUs, combined as 'others'
fung.L2 <- melt(fung.L2,id.vars = "Group.1")
fung.L2<-cSplit(fung.L2, "Group.1", ":")
names(fung.L2)<-c("Fungi","Relative_Abundance", "Sampletime", "Direction", "Distance")
fung.L2$Fungi<-"Other"

fung.bind<-rbind(fung.L1,fung.L2) # combine the domiant and rare OTUs

ggplot(fung.bind, aes(x = interaction (Direction,factor(Distance)), y = Relative_Abundance,fill=Fungi)) +
  geom_bar(stat='identity', position = "fill" )+  ###add < , position = "fill"  > for relative abundance
  labs(x="Location",y = "Percent of fungal reads")+
  facet_wrap(~Sampletime )+
  theme_bw()+
  theme(strip.text = element_text(size = 20,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=20, face="bold"),
        legend.text = element_text(colour="black", size=20, face="bold"),
        axis.text=element_text(size=10,face="bold",angle = 90),
        axis.title=element_text(size=20,face="bold"))+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("#ff00ff","#00ff00", "deepskyblue", "gold", "red", "navy", "darkgreen","maroon3", "black", "bisque", "grey")) 


ggplot(fung.bind, aes(x = interaction (Direction,factor(Distance)), y = Relative_Abundance,fill=Fungi)) +
  geom_bar(stat='identity', position = "fill" )+  ###add < , position = "fill"  > for relative abundance
  labs(x="Location",y = "Percent of fungal reads")+
  facet_wrap(~Sampletime )+
  theme_bw()+
  guides(fill="none")+
  theme(strip.text = element_text(size = 20,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=20, face="bold"),
        legend.text = element_text(colour="black", size=20, face="bold"),
        axis.text=element_text(size=10,face="bold",angle = 90),
        axis.title=element_text(size=20,face="bold"))+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("#ff00ff","#00ff00", "deepskyblue", "gold", "red", "navy", "darkgreen","maroon3", "black", "bisque", "grey")) 


```

